#!/bin/bash
set -xe

set -e
shopt -s dotglob
echo "---> Installing application source ..."
mv /tmp/src/* ./


pip install -r requirements.txt

# set permissions for any installed artifacts
fix-permissions /opt/app-root
